# Generated by Django 5.2 on 2025-04-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Technology', 'Technology'), ('Daily', 'Daily'), ('Default', 'Default')], default='Default', max_length=20),
        ),
    ]
