# Generated by Django 5.2 on 2025-04-27 18:20

import app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=app.models.get_guest_user, on_delete=models.SET(app.models.get_guest_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
